[features]
seeds = false
skip-lint = false
[programs.devnet]
counter = "GjhgEtT1bkmceCyQ4ozKtq26kG88pz6BoXsK9EAofxYz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/heisenberg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
